survey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('yevrus/', include('yevrus.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

yevrus/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'yevrus'

urlpatterns = [
    path('', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('register/', views.register, name='register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
            name='activate'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', views.change_password, name='change_password'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('mysurveys/', views.mysurveys, name='mysurveys'),
    path('createsurveys/', views.createsurveys, name='createsurveys'),
    path('editsurvey/<survey_key>', views.editsurvey, name='editsurvey'),
    path('deletesurvey/<survey_key>', views.deletesurvey, name='deletesurvey'),
    path('surveys/<survey_key>', views.surveyresponse, name='surveyresponse'),
    path('showresponse/<survey_key>', views.show_response, name='show_response'),
    path('showresponse/<survey_key>/<response_id>', views.show_response_id, name='show_response_id'),
    path('export/<survey_key>', views.export_to_xls, name='export_to_xls'),
    path('get_chart/', views.get_chart, name='get_chart'),
    path('get_statistics/<survey_key>', views.get_statistics, name='get_statistics'),
    path('archive/<survey_key>', views.archive_survey, name='archive_survey'),
    path('publish/<survey_key>', views.publish_survey, name='publish_survey'),
]

yevrus/forms.py
import datetime
import ast
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SurveyForm(forms.Form):

    def __init__(self, *args, **kwargs):
        survey = kwargs.pop('survey')
        super(SurveyForm, self).__init__(*args, **kwargs)
        questions_set = survey.question_set.all().order_by('id_in_survey')

        for i, question in enumerate(questions_set):
            if question.type == '0':
                self.fields['question_%s' % i] = forms.CharField(label=question.title, widget=forms.TextInput(
                    attrs={'class': 'form-control'}))
            if question.type == '1':
                choice_set = question.choice_set.all().order_by('id_in_question')
                options = [(c.id_in_question, c.label) for c in choice_set]
                self.fields['question_%s' % i] = forms.ChoiceField(choices=options, widget=forms.RadioSelect,
                                                                   label=question.title)
            if question.type == '2':
                choice_set = question.choice_set.all().order_by('id_in_question')
                options = [(c.id_in_question, c.label) for c in choice_set]
                self.fields['question_%s' % i] = forms.MultipleChoiceField(choices=options,
                                                                           required=False, label=question.title,
                                                                           widget=forms.CheckboxSelectMultiple)


class ResponseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        response = None
        survey = kwargs.pop('survey')
        if 'user' in kwargs:
            user = kwargs.pop('user')
            response = survey.response_set.get(user=user)

        elif 'response_id' in kwargs:
            response_id = kwargs.pop('response_id')
            response = survey.response_set.get(id=response_id)

        super(ResponseForm, self).__init__(*args, **kwargs)
        questions_set = survey.question_set.all().order_by('id_in_survey')
        answer = response.answer_set.all().order_by('id_in_response')
        for i, question in enumerate(questions_set):
            if question.type == '0':
                self.fields['question_%s' % i] = forms.CharField(label=question.title, initial=answer[i].answer,
                                                                 disabled=True,
                                                                 widget=forms.TextInput(
                                                                     attrs={'class': 'form-control'}))
            if question.type == '1':
                choice_set = question.choice_set.all().order_by('id_in_question')
                options = [(c.id_in_question, c.label) for c in choice_set]
                self.fields['question_%s' % i] = forms.ChoiceField(choices=options,
                                                                   initial=answer[i].answer,
                                                                   disabled=True,
                                                                   widget=forms.RadioSelect,
                                                                   label=question.title)
            if question.type == '2':
                choice_set = question.choice_set.all().order_by('id_in_question')
                options = [(c.id_in_question, c.label) for c in choice_set]
                self.fields['question_%s' % i] = forms.MultipleChoiceField(choices=options,
                                                                           disabled=True,
                                                                           initial=ast.literal_eval(answer[i].answer),
                                                                           required=False, label=question.title,
                                                                           widget=forms.CheckboxSelectMultiple)

yevrus/views.py
import requests
import xlwt
import ast

from yevrus.xls_sheet_handle import FitSheetWrapper
from django.conf import settings
from django.core.mail import EmailMessage
from django.urls import reverse
from django.forms import formset_factory, BaseFormSet
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from datetime import datetime

from .models import *
from .forms import *
from .tokens import account_activation_token


def log_in(request):
    if request.user.is_authenticated:
        return redirect('yevrus:dashboard')

    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('yevrus:dashboard')
            else:
                return render(request, 'yevrus/login.html', {'form': form, 'user': user})
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'yevrus/login.html', context)


def log_out(request):
    logout(request)
    return redirect('yevrus:login')


def register(request):
    if request.user.is_authenticated:
        return redirect('yevrus:dashboard')

    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()

            if result['success']:
                user = form.save(commit=False)
                user.is_active = False
                user.save()
                current_site = get_current_site(request)
                mail_subject = 'Activate your account.'
                message = render_to_string('yevrus/account_active_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                })
                to_email = form.cleaned_data.get('email')
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
                messages.success(request, 'An activation link has been sent to your email address.' \
                                          'Please Check your Inbox to confirm before login.')
                return redirect('yevrus:login')
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
    else:
        form = SignupForm()

    context = {'form': form}
    return render(request, 'yevrus/register.html', context)


def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        messages.success(request, 'Thank you for your email confirmation. Now you have logged In')
        return redirect('yevrus:dashboard')
    else:
        messages.error(request, 'Activation link is invalid!')
        return redirect('yevrus:login')


@login_required(login_url='/yevrus/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('yevrus:dashboard')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'yevrus/change_password.html', {'form': form})


@login_required(login_url='/yevrus/')
def dashboard(request):
    user = request.user
    latest_survey_list = Survey.objects.exclude(user=user).exclude(is_published=0)
    response_list = Response.objects.filter(user=user).values('survey').distinct()
    filled_survey_list = Survey.objects.filter(id__in=response_list)
    context = {
        'latest_survey_list': latest_survey_list,
        'filled_survey_list': filled_survey_list,
    }
    return render(request, 'yevrus/dashboard.html', context)


@login_required(login_url='/yevrus/')
def mysurveys(request):
    user = request.user
    publish_survey_list = Survey.objects.filter(user=user, is_published=1, is_done=False)
    private_survey_list = Survey.objects.filter(user=user, is_published=0, is_done=False)
    done_survey_list = Survey.objects.filter(user=user, is_done=True)
    response_list = Response.objects.filter(user=user).values('survey').distinct()
    filled_survey_list = Survey.objects.filter(id__in=response_list)
    context = {
        'publish_survey_list': publish_survey_list,
        'private_survey_list': private_survey_list,
        'filled_survey_list': filled_survey_list,
        'done_survey_list': done_survey_list,
    }
    if not publish_survey_list and not private_survey_list and not done_survey_list and not filled_survey_list:
        context['is_empty'] = True
    return render(request, 'yevrus/my_surveys.html', context)


@login_required(login_url='/yevrus/')
def createsurveys(request):
    if request.method == 'POST':
        user = request.user
        survey = user.survey_set.create(title=request.POST.get('title'), is_published=request.POST.get('is_published'))
        try:
            survey.save()
            question_count = int(request.POST.get('question_count'))
            for i in range(0, question_count):
                question_id = request.POST.get('question_%s[id_in_survey]' % i)
                question_type = request.POST.get('question_%s[type]' % i)
                question_text = request.POST.get('question_%s[text]' % i)
                question_option_raw = request.POST.get('question_%s[option]' % i).split('\n')
                question_option = []
                for option in question_option_raw:
                    if option:
                        question_option.append(option)
                question = survey.question_set.create(id_in_survey=question_id, type=question_type, title=question_text)
                question.save()
                if question_type != '0':
                    for j, option in enumerate(question_option):
                        choice = question.choice_set.create(label=option, id_in_question=j)
                        choice.save()
        except:
            survey.delete()
            return JsonResponse({'message': 'An error occur. Please try a gain.'})
        return JsonResponse({'message': 'Success!'})
    else:
        return render(request, 'yevrus/create_surveys.html')


@login_required(login_url='/yevrus/')
def editsurvey(request, survey_key):
    survey = get_object_or_404(Survey, key=survey_key)
    questions_set = survey.question_set.all().order_by('id_in_survey')

    if request.method == 'POST':
        survey.delete()
        user = request.user
        survey = user.survey_set.create(title=request.POST.get('title'), is_published=request.POST.get('is_published'),
                                        key=survey_key)
        try:
            survey.save()
            question_count = int(request.POST.get('question_count'))
            for i in range(0, question_count):
                question_id = request.POST.get('question_%s[id_in_survey]' % i)
                question_type = request.POST.get('question_%s[type]' % i)
                question_text = request.POST.get('question_%s[text]' % i)
                question_option_raw = request.POST.get('question_%s[option]' % i).split('\n')
                question_option = []
                for option in question_option_raw:
                    if option:
                        question_option.append(option)
                question = survey.question_set.create(id_in_survey=question_id, type=question_type, title=question_text)
                question.save()
                if question_type != '0':
                    for j, option in enumerate(question_option):
                        choice = question.choice_set.create(label=option, id_in_question=j)
                        choice.save()
        except:
            survey.delete()
            return JsonResponse({'message': 'An error occur. Please try a gain.'})
        return JsonResponse({'message': 'Success!'})
    else:

yevrus/templates/yevrus/account_active_email.html
{% autoescape off %}
    Hi {{ user.username }},

    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'yevrus:activate' uidb64=uid token=token %}

    Sincerely,
    Polls and Survey Team
{% endautoescape %}

yevrus/templates/yevrus/dashboard.html
{% extends 'yevrus/includes/surveys_layout.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">{{ message }}</div>
                    {% elif message.level ==  DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <h2>Survey list</h2>
            <hr>
            {% if latest_survey_list %}
                <div class="row">
                {% for survey in latest_survey_list %}
                    <div class="form-group col-sm-4">
                    {% if survey in filled_survey_list %}
                        <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ survey.title }}</h3>
                        </div>
                        <div class="panel-body">
                        <a type="button" class="btn btn-info"
                           href="{% url 'yevrus:show_response' survey.key %}">Review response</a>
                    {% else %}
                        <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ survey.title }}</h3>
                        </div>
                        <div class="panel-body">
                        <a type="button" class="btn btn-primary"
                           href="{% url 'yevrus:surveyresponse' survey.key %}">Answer</a>
                    {% endif %}
                </div>
                </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
                <p>No surveys are available.</p>
            {% endif %}
            </div>
            </div>
{% endblock %}

yevrus/templates/yevrus/my_surveys.html
{% extends 'yevrus/includes/surveys_layout.html' %}

{% block title %}
    My surveys
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success" role="alert">{{ message }}</div>
                    {% elif message.level ==  DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger" role="alert">{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <h2>Your surveys list</h2>
            <a type="button" class="btn btn-success" href="{% url 'yevrus:createsurveys' %}">Create new survey</a>
            <hr>

            {% if is_empty %}
                <p>You currently have no surveys.</p>
            {% else %}
                <div class="form-group" style="padding-left: 15px">
                    <h3>Published surveys</h3>
                    {% if publish_survey_list %}
                        <div class="row">
                            {% for survey in publish_survey_list %}
                                <div class="form-group col-sm-6">
                                    <div class="panel panel-primary">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">{{ survey.title }}</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <a type="button" class="btn btn-danger"
                                                   href="{% url 'yevrus:deletesurvey' survey.key %}">
                                                    Delete
                                                </a>
                                                <a type="button" class="btn btn-info"
                                                   href="{% url 'yevrus:get_statistics' survey.key %}">Check
                                                    result
                                                </a>
                                                <button type="button" class="btn btn-primary" data-toggle="modal"
                                                        data-target="#linkModal{{ survey.pk }}">
                                                    Get Link Survey
                                                </button>
                                                <a type="button" class="btn btn-warning"
                                                   href="{% url 'yevrus:archive_survey' survey.key %}">Archive
                                                </a>
                                            </div>
                                            <div class="modal fade" id="linkModal{{ survey.id }}" tabindex="-1"
                                                 role="dialog"
                                                 aria-labelledby="linkModalLabel"
                                                 aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="linkModalLabel{{ survey.id }}">
                                                                <b>Share
                                                                    link</b></h5>
                                                        </div>
                                                        <div class="modal-body"
                                                             style="padding-right: 10%; padding-left: 10%">
                                                            <div class="row">
                                                                <div class="col-sm-1" style="">
                                                                    <label class="control-label"
                                                                           for="link-survey{{ survey.id }}">Link</label>
                                                                </div>
                                                                <div class="col-sm-11">
                                                                    <input type="text" class="form-control"
                                                                           id="link-survey{{ survey.id }}"
                                                                           maxlength="255" required
                                                                           value="{{ request.get_host }}{% url 'yevrus:surveyresponse' survey.key %}">
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-success"
                                                                    onclick="copy('link-survey{{ survey.id }}')">Copy
                                                            </button>

                                                            <button type="button" class="btn btn-danger"
                                                                    data-dismiss="modal">Close
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <hr style="margin-left: 30px">
                <div class="form-group" style="padding-left: 15px">
                    <h3>Unpublished surveys</h3>
                    {% if private_survey_list %}
                        <div class="row">
                            {% for survey in private_survey_list %}
                                <div class="form-group col-sm-6">
                                    <div class="panel panel-danger">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">{{ survey.title }}</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <a type="button" class="btn btn-danger"
                                                   href="{% url 'yevrus:deletesurvey' survey.key %}">
                                                    Delete
                                                </a>
                                                <a type="button" class="btn btn-primary"
                                                   href="{% url 'yevrus:editsurvey' survey.key %}">Edit
                                                </a>
                                                <a type="button" class="btn btn-warning"
                                                   href="{% url 'yevrus:publish_survey' survey.key %}">Publish
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <hr style="margin-left: 30px">
                <div class="form-group" style="padding-left: 15px">
                    <h3>Filled surveys</h3>
                    {% if filled_survey_list %}
                        <div class="row">
                            {% for survey in filled_survey_list %}
                                <div class="form-group col-sm-6">
                                    <div class="panel panel-info">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">{{ survey.title }}</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <a type="button" class="btn btn-info"
                                                   href="{% url 'yevrus:show_response' survey.key %}">
                                                    Review Response
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                <hr style="margin-left: 30px">
                <div class="form-group" style="padding-left: 15px">
                    <h3>Archived surveys</h3>
                    {% if done_survey_list %}
                        <div class="row">
                            {% for survey in done_survey_list %}
                                <div class="form-group col-sm-6">
                                    <div class="panel panel-warning">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">{{ survey.title }}</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <a type="button" class="btn btn-danger"
                                                   href="{% url 'yevrus:deletesurvey' survey.key %}">
                                                    Delete
                                                </a>
                                                <a type="button" class="btn btn-info"
                                                   href="{% url 'yevrus:get_statistics' survey.key %}">Check
                                                    result
                                                </a>
                                                <a type="button" class="btn btn-warning"
                                                   href="{% url 'yevrus:archive_survey' survey.key %}">Unarchive
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            {% endif %}


        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        function copy(id) {
            let copyText = document.getElementById(id);
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
        }
    </script>
{% endblock %}

yevrus/templates/yevrus/unavailable_survey.html
{% extends 'yevrus/includes/surveys_layout.html' %}

{% block title %}
    Response
{% endblock %}

{% block content %}
    <div class="container">
    <div class="jumbotron">
        <h2>Survey unavailable</h2>
        <hr>
    </div>
{% endblock %}